### ISSUE TITLE
fillfacets should take stdin

### ISSUE THREAD

**Issue by dnomadb** [mapbox/make-surface#61]
[`fillfacets`](https://github.com/mapbox/make-surface/blob/master/makesurface/scripts/fill_facets.py) should be able to take stdin of `geojson` geometries

cc @ian29 @rclark

**Comment by dnomadb** [comment]
Still working on even getting stdin to work - so far (for a test run of `echo test | makesurface fillfacets inputraster.tif ... ` it seems the only was is to specify the input explicitly as a file, eg:
```
@click.argument('infile', default='-', required=False, type=click.File('rb'))
```
Otherwise, it is recognizing it as a string, "-". Tried a number of variations, but was hoping @sgillies could take a quick look?

https://github.com/mapbox/make-surface/blob/443baa454f0b393c26a027ed5e283a138279a1d0/makesurface/scripts/cli.py#L76

Also - @ian29 could I get a sample of what get-triangles.js is going to be outputting?

**Comment by sgillies** [comment]
@dnomadb drop the type in the argument decorator, let it be a string like below.

example.py:

```python
import click

@click.command()
@click.argument('input', default='-', required=False)
def example(input):
    try:
        src = click.open_file(input).readlines()
    except IOError:
        src = [input]
    for line in input:
        click.echo(line)

if __name__ == '__main__':
    example()
```

That will handle file names, stdin, or text input. So all three of these forms will work:

```bash
$ python example.py foo.json # prints each line of foo.json
$ echo '{"foo": 1}' | python example.py # prints out the line of JSON text
$ python example.py '{"foo": 1}' # also prints out the same JSON text
```

**Comment by dnomadb** [comment]
So, I had tried that, but am still only getting a string of `-`. With `example.py` above, it is the same:
```
▶ echo '{"foo": 1}' | python example.py
-
```
However, like this, it works (no checks for file):
```python
import click

@click.command()
@click.argument('input', default='-', required=False, type=click.File('r'))
def example(input):
    click.echo(input.read())

if __name__ == '__main__':
    example()
```
Which runs like:
```
▶ echo '{"foo": 1}' | python example.py
{"foo": 1}
```
I'll keep trying tomorrow - thanks for the tips!

**Comment by sgillies** [comment]
@dnomadb I got it: `open_file` is [new in click 3.0](http://click.pocoo.org/3/utils/#intelligent-file-opening). Upgrade and you're all set.

**Comment by dnomadb** [comment]
Not sure that is it either - I tried upgrading (w/ `pip install click --upgrade`). I am running python 2.7, might this be why?
```
▶ pip freeze | grep click
click==3.3
```

**Comment by sgillies** [comment]
@dnomadb a string of '-' is actually what you want. Look at https://github.com/mapbox/mercantile/blob/master/mercantile/scripts/__init__.py#L116 -- the value of `input` is '-' there. `open_file('-')` returns `sys.stdin`. But if you don't want literal JSON value arguments and just file/stdin, you can keep it like you've got it.

**Comment by dnomadb** [comment]
`stdin` from `get-triangles.js` is now accepted as an input to `makesurface fillfacets` as of https://github.com/mapbox/make-surface/commit/ce866de26b12bbdde47ef016063c1ba4489ec8d9

**Comment by ian29** [comment]
:tada: :dancer: :pray: :dancer: :tada:
