### ISSUE TITLE
Extra row of triangles generated outside of top bounds

### ISSUE THREAD

**Issue by MateoV** [mapbox/make-surface#71]
@dnomadb There looks to be some sort of rounding error with the top bounds that causes the very top row of triangles to be created outside the bounds:

```
{"type":"Feature","properties":{"quadtree":"s2s2s2s3s3s2s3s3s2n2n2n"},"geometry":{"type":"Polygon","coordinates":[[[-142.03125,85.0511287798066],[-141.85546875,85.0662697036382],[-142.03125,85.0662697036382],[-142.03125,85.0511287798066]]]}}
```

notice that `85.0662697036382` is greater than the web mercator bound of `85.0511287798066`

**Comment by MateoV** [comment]
This may also be causing a row to be left out at the bottom, as the min bound of triangles is at `-85.035941506574`

**Comment by dnomadb** [comment]
Fixed by negative padding the bounds generated from a `--tile` option.
