### ISSUE TITLE
divide by zero on smoosh'd HRRR data

### ISSUE THREAD

**Issue by ian29** [mapbox/make-surface#80]
to reproduce: 

1. [download some HRRR wind data](http://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_2d.pl?file=hrrr.t11z.wrfsfcf00.grib2&var_WIND=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fhrrr.20150212
)
2. `gribdoctor smoosh -dev hrrr-wind.grib hrrr-out.tif`
3. `makesurface triangulate 11 --tile 3 3 3 | makesurface fillfacets -b 1 wind hrrr-out.tif`
4. see the gross "divide be zero" :[

this is using latest gribdoctor + makesurface

**Comment by ian29** [comment]
@dnomadb ooo would a cheap work around / stop gap be to always smoosh at least 1 HRRR  grib that is unlikely to have a nodata value? like smoosh temp and wind?

**Comment by dnomadb** [comment]
@ian29 the no data does not come from the actual raster, I think, it comes
from the edge areas that when projected, are outside the raster bounds. So
actually, technically, it's not "nodata" there is just no data.

**Comment by ian29** [comment]
ah, gross. what booger.

**Comment by dnomadb** [comment]
Fixed with https://github.com/mapbox/make-surface/pull/81
